# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: run

  init:
    desc: "Initialize your workspace."
    aliases:
      - "i"
    preconditions:
      - sh: "[ ! -f .env ]"
        msg: "Workspace has already been initialized."
    silent: true
    cmds:
      - echo 'SESSION_TOKEN=""' > .env
      - |
        echo ".env file has been created. Please grab your session token from the adventofcode.com \
        website and paste it into the SESSION_TOKEN variable in the .env file."

  new:
    desc: "Create a new day project."
    aliases:
      - "n"
    cmds:
      - bash scripts/new.sh

  commit:
    desc: "Commit the latest day solution."
    aliases:
      - "c"
    cmds:
      - bash scripts/commit.sh

  test:
    desc: "Run all unit tests."
    aliases:
      - "t"
    cmds:
      - cargo test

  run:
    aliases:
      - "r"
    desc: "Run solution with user input."
    cmds:
      - bash scripts/run.sh {{.CLI_ARGS}}

  runtest:
    aliases:
      - "rt"
    desc: "Run solution with test input."
    cmds:
      - bash scripts/run.sh {{.CLI_ARGS}} --test

  releaserun:
    aliases:
      - "rr"
    env:
      RELEASE: "true"
    cmds:
      - bash scripts/run.sh {{.CLI_ARGS}}

  releaseruntest:
    aliases:
      - "rrt"
    env:
      RELEASE: "true"
    cmds:
      - bash scripts/run.sh {{.CLI_ARGS}} --test
